typography_spectrum: 0.48246838385239244
color:
  brandStrength: 0.9248656630516052
  lightness: 0.18659388599917293
  saturation: 0.3724855459295213
  rhythmicContrast: 0.9071969680953771
  brandColors:
    - '#F5871F'
    - '#C8CBCD'
    - '#CA1C24'
    - '#0057C9'
    - '#3FA3DA'
layout_spectrum: 0.12032449594698846
author:
  name: Paul Hannah
  email: paul@memetec.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/aa17e6f6-23b7-4f5d-a1a3-cb38e4eb6c28.png
name: memetec
navigation:
  - name: About
    id: 5437d35b-78c4-48c7-b8f7-d99af7390dec
    type: content
title: memetec
description: technology -- evolved
